[package]
name = "vlan_scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
ipnetwork = "0.21.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
chrono = "0.4.39"
ping-rs = "0.1.2"
config = "0.15.4"
regex = "1.11.1"
threadpool = "1.8.1"
